### ISSUE TITLE
(no issues at all please see below)

### ISSUE THREAD

**Issue by PC-Doctor666** [Kaj9296/Asym#5]
Forgive me opening an issue on ya like this. I just wanted to say I'm really impressed with your project. Keep it up good sir/ma'am

**Comment by KaiNorberg** [comment]
I didn't actually notice you opened and closed an issue until now. Anyway, let me say thank you for the kind words... 3 months too late lol.

As I believe you know, an issue is really not the right place for this, my email is now publicly available on my GitHub "KN.KaiNorberg@gmail.com" so feel free to contact me via email in the future. :)
